### ISSUE TITLE
Object.assign

### ISSUE THREAD

**Issue by webpro** [low-ghost/redux-node-logger#2]
Hi, wanted to use your module, but it throws because..

``` js
var _extends = Object.assign || function ...
```

..gets transpiled as..

``` js
var _Object$assign = require('babel-runtime/core-js/object/assign')['default'];

var _Object$keys = require('babel-runtime/core-js/object/keys')['default'];
```

And in my project, I don't want to use that runtime.

The weird thing is, if I just `npm run build`, things are transpiled without the `babel-runtime` being required. That's different from `build/index.js` if I `npm install` this.

**Comment by low-ghost** [comment]
hmm that is odd. I don't know why I bothered with the extend/assign polyfill, I prefer the es7/2016/whatever object spread syntax anyhow. let me know if the branch webpro-fix works for you

**Comment by webpro** [comment]
Yup, working fine! Thanks.

**Comment by webpro** [comment]
@low-ghost Could you publish a new version to npm? Thanks!

**Comment by low-ghost** [comment]
yep, sorry for being so slow. Updated to version 0.0.3
